### ISSUE TITLE
Learning gem5 tutorial presentation is down (ASPLOS 2018)

### ISSUE THREAD

**Issue by pedroexenberger** [shioyadan/Konata#10]
A presentation of the tool in ASPLOS 2018 is provided in the repo description, but apparently the link (http://learning.gem5.org/tutorial/presentations/vis-o3-gem5.pdf) is unreachable. 
Is it possible to upload the presentation somewhere else?

**Comment by shioyadan** [comment]
I have uploaded the presentation file to a different location and fixed the link. Also, I have slightly modified the description to reflect the current version. Please check it. 
Thank you!
