### ISSUE TITLE
Does W command work?

### ISSUE THREAD

**Issue by Bitmanyga** [shioyadan/Konata#8]
Could you help me - it seems like W command does not work, i don't see any arrows. What am I doing wrong?
```
//--------------------------------------
I	3	4	0
L	3	0	main_comment: test_3
S	3	0	st_3
C	5			
R	3	104	0
I	4	4	0	
L	4	0	main_comment: test_4
S	4	1	st_4
I	5	5	0	
L	5	0	main_comment: test_5
S	5	2	st_5
I	6	6	0	
L	6	0	main_comment: test_6
C	2
S	6	3	st_6
R	5	191	1
C	7
E	5	2	st_5

W	5	6	0  // arrows???

C	6

```

**Comment by shioyadan** [comment]
Dependency arrows are shown between stages with "X" in the stage name. Please try to make stages with "X" in the stage name. I forgot to mention this in my documentation, so I will add it to my documentation. Thanks!

**Comment by Bitmanyga** [comment]
I made X-name by stages 4 and 6, but nothing happened 
![image](https://user-images.githubusercontent.com/59740338/190927746-c63e2691-d302-4385-8af4-4a1e67a1fad8.png)

```
I	3	4	0
L	3	0	main_comment: test_3
S	3	0	st_3	
C	5			
R	3	104	0	

I	4	4	0	
L	4	0	main_comment: test_4
S	4	1	X // X-name too

I	5	5	0	
L	5	0	main_comment: test_5
S	5	2	st_5
I	6	6	0	

L	6	0	main_comment: test_6
C	2
S	6	3	X  // X-name 
R	5	191	1

C	7
E	5	2	st_5
W	6	4	0 // waiting dependence between 6 and 4
C	6

```

**Comment by shioyadan** [comment]
* To show dependency arrows, "X" stages must be closed by the "E" command or another successor stage must be started. I added the "E" commands for ID 4 and 6 in the following example. 
* The consumer and producer arguments for the "W" are reversed in your trace.
* You can see debug messages, which may include parsing errors or warnings, in the console in DevTool. You can enable DevTool from Help -> Toggle DevTool.
![image](https://user-images.githubusercontent.com/6016305/190959876-b611d077-f9f2-437d-af0f-ef91ab9f42fd.png)
```
Kanata	0004
I	3	3	0
L	3	0	main_comment: test_3
S	3	0	st_3	
C	5			
R	3	104	0	
I	4	4	0	
L	4	0	main_comment: test_4
S	4	0	X
I	5	5	0	
L	5	0	main_comment: test_5
S	5	0	st_5
I	6	6	0	
L	6	0	main_comment: test_6
C	2
E	4	0	X
S	6	0	X
R	5	5	1
C	7
E	5	0	st_5
E	6	0	X
W	6	4	0
C	6
```

**Comment by shioyadan** [comment]
* Lane id must be consistent in each instruction (typically they should be zero). Otherwise, the instruction stages are not closed properly. You used inconsistent lane id in each instruction in your trace.

**Comment by Bitmanyga** [comment]
Thank you for your answers! I got arrows in my visualisation!
![image](https://user-images.githubusercontent.com/59740338/191022935-1082cc7c-9cf2-438c-9aad-672adce413ef.png)

I thought that <LANE_ID> just affects on a color of stage-block. Could you explain me what is <LANE_ID> and how does i need to use it properly?

**Comment by shioyadan** [comment]
Congratulations!
I added some detail to the document. Please see the following part.
https://github.com/shioyadan/Konata/blob/master/docs/kanata-log-format.md#lane
